import type { Metadata } from "next";
import "../globals.css";
import SideNavigation from "@/components/SideNavigation";
import TopNavigation from "@/components/TopNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="flex h-[100vh]">
          <SideNavigation />
          <div className="flex-1 overflow-auto">
            <TopNavigation />
            <div className="flex-1 p-2 overflow-auto">
              {children}
            </div>
          </div>
        </div>
  );
}
